import React, { useState, useEffect } from "react"
import { ChevronDown, ChevronUp, Bot, FileText, CheckCircle2, AlertTriangle, AlertCircle } from "lucide-react"
import { Card, CardContent } from "./ui/card"
import { Badge } from "./ui/badge"
import { motion, AnimatePresence } from "framer-motion"

interface ReasoningPanelProps {
  reasoning: string
  confidence: number
  signalsUsed: string[]
  signalsSkipped: string[]
}

const TypewriterText = ({ text }: { text: string }) => {
  const [displayedText, setDisplayedText] = useState("")
  
  useEffect(() => {
    setDisplayedText("")
    let i = 0
    const intervalId = setInterval(() => {
      setDisplayedText(text.slice(0, i))
      i += 3 // Type 3 characters at a time for smoother, faster typing of long text
      if (i > text.length + 3) {
        clearInterval(intervalId)
        setDisplayedText(text) // ensure exact text matches at the end
      }
    }, 15) // Speed of typing
    
    return () => clearInterval(intervalId)
  }, [text])

  return (
    <span>
      {displayedText}
      <motion.span 
        animate={{ opacity: [1, 0] }} 
        transition={{ repeat: Infinity, duration: 0.8 }}
        className="inline-block w-1.5 h-4 ml-1 bg-primary align-middle"
      />
    </span>
  )
}

export function ReasoningPanel({ reasoning, confidence, signalsUsed, signalsSkipped }: ReasoningPanelProps) {
  const [isExpanded, setIsExpanded] = useState(true)

  return (
    <Card className="border-white/10 bg-card/40 backdrop-blur-xl shadow-2xl overflow-hidden rounded-3xl relative group">
      {/* Subtle top glow */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-primary/50 to-transparent opacity-50" />
      
      <div 
        className="flex items-center justify-between p-6 cursor-pointer hover:bg-white/5 transition-colors z-10 relative"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-4">
          <motion.div 
            animate={{ scale: [1, 1.05, 1], rotate: [0, 5, -5, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
            className="p-3 bg-primary/20 rounded-2xl shadow-[0_0_15px_rgba(99,102,241,0.3)] border border-primary/30"
          >
            <Bot className="w-6 h-6 text-primary" />
          </motion.div>
          <div>
            <h3 className="font-black text-lg tracking-wide flex items-center gap-3 drop-shadow-sm">
              AI Core Analysis
              {confidence < 0.8 && (
                <Badge variant="outline" className="text-xs bg-amber-500/10 border-amber-500/30 text-amber-500 shadow-sm px-2 py-0.5">
                  <AlertTriangle className="w-3 h-3 mr-1.5" />
                  Limited Data ({Math.round(confidence * 100)}%)
                </Badge>
              )}
            </h3>
            <p className="text-xs text-muted-foreground/80 font-medium uppercase tracking-widest mt-1">
              Generated by LLM Engine
            </p>
          </div>
        </div>
        <div className="p-2 hover:bg-white/10 rounded-full transition-colors border border-transparent hover:border-white/10">
          <motion.div animate={{ rotate: isExpanded ? 180 : 0 }} transition={{ duration: 0.3 }}>
            <ChevronDown className="w-6 h-6 text-muted-foreground" />
          </motion.div>
        </div>
      </div>
      
      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: "easeInOut" }}
          >
            <CardContent className="p-6 pt-0 border-t border-white/5 mt-2">
              <div className="prose prose-sm dark:prose-invert max-w-none text-foreground/90 leading-relaxed bg-black/40 p-6 rounded-2xl border border-white/5 shadow-inner whitespace-pre-wrap font-medium">
                <TypewriterText text={reasoning.replace(/\*\*/g, '')} />
              </div>
              
              <div className="mt-6 flex flex-wrap items-center gap-4 text-xs font-bold uppercase tracking-wider">
                <div className="flex items-center gap-2 text-muted-foreground">
                  <FileText className="w-4 h-4" />
                  <span>Signals Analyzed:</span>
                </div>
                
                <div className="flex flex-wrap gap-2">
                  {signalsUsed.map(signal => (
                    <Badge key={signal} variant="secondary" className="bg-green-500/10 text-green-500 border-green-500/20 shadow-sm px-3 py-1">
                      <CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />
                      {signal}
                    </Badge>
                  ))}
                  
                  {signalsSkipped.map(signal => (
                    <Badge key={signal} variant="secondary" className="bg-amber-500/10 text-amber-500 border-amber-500/20 shadow-sm px-3 py-1">
                      <AlertCircle className="w-3.5 h-3.5 mr-1.5" />
                      {signal}
                    </Badge>
                  ))}
                </div>
              </div>
            </CardContent>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  )
}
